// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wheelsUN_transaction_db.Data;

#nullable disable

namespace wheelsUN_transaction_db.Migrations
{
    [DbContext(typeof(wheelsUN_transaction_context))]
    partial class wheelsUN_transaction_contextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("wheelsUN_transaction_db.Data.CreditCard", b =>
                {
                    b.Property<int>("creditCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("creditCardId"));

                    b.Property<int>("TransactionstransactionID")
                        .HasColumnType("int");

                    b.Property<string>("expirationDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("securityCode")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("creditCardId");

                    b.HasIndex("TransactionstransactionID");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("wheelsUN_transaction_db.Data.Transaction", b =>
                {
                    b.Property<int>("transactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("transactionID"));

                    b.Property<int>("creditCardId")
                        .HasColumnType("int");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("driverAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("driverCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("driverCountry")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("driverEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("driverHomephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("driverId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("driverName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("driverPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("driverPostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("referenceCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("transactionIdPay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userCountry")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userHomephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userPostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("transactionID");

                    b.HasIndex("creditCardId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("wheelsUN_transaction_db.Data.CreditCard", b =>
                {
                    b.HasOne("wheelsUN_transaction_db.Data.Transaction", "Transactions")
                        .WithMany("CreditCards")
                        .HasForeignKey("TransactionstransactionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("wheelsUN_transaction_db.Data.Transaction", b =>
                {
                    b.HasOne("wheelsUN_transaction_db.Data.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("creditCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("wheelsUN_transaction_db.Data.Transaction", b =>
                {
                    b.Navigation("CreditCards");
                });
#pragma warning restore 612, 618
        }
    }
}
